"""add_agent_publish_table

Revision ID: 11347c08a5c7
Revises: add_sub_agent_ids_001
Create Date: 2026-05-07 11:52:36.349383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '11347c08a5c7'
down_revision: Union[str, None] = 'add_sub_agent_ids_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_publishes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_publishes_agent_id_is_active', 'agent_publishes', ['agent_id', 'is_active'], unique=False)
    op.drop_table('pipeline_sub_agents')
    op.add_column('agents', sa.Column('published_version', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'last_published_at')
    op.drop_column('agents', 'published_version')
    op.create_table('pipeline_sub_agents',
    sa.Column('pipeline_id', sa.BIGINT(), nullable=False),
    sa.Column('agent_id', sa.BIGINT(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'agent_id')
    )
    op.drop_index('ix_agent_publishes_agent_id_is_active', table_name='agent_publishes')
    op.drop_table('agent_publishes')
    # ### end Alembic commands ###
