"""phase8_mcp_server_and_config_fields

Revision ID: 492862c9a96f
Revises: 
Create Date: 2026-04-26 22:59:10.378540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '492862c9a96f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport_type', sa.Enum('STDIO', 'HTTP_SSE', name='mcptransporttype'), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('auth_type', sa.Enum('NONE', 'API_KEY', 'BEARER_TOKEN', 'BASIC_AUTH', name='mcpauthtype'), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'CONNECTED', 'DISCONNECTED', 'ERROR', name='mcpserverstatus'), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('agents', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='agentstatus'), nullable=False))
    op.add_column('agents', sa.Column('temperature', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('max_tokens', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('intent_recognition_enabled', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('intent_model_id', sa.BigInteger(), nullable=True))
    op.add_column('agents', sa.Column('intent_confidence_threshold', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('intent_system_prompt', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('intent_entity_schema', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('routing_strategy', sa.String(length=32), nullable=False))
    op.add_column('agents', sa.Column('routing_model_id', sa.BigInteger(), nullable=True))
    op.add_column('agents', sa.Column('routing_system_prompt', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('routing_threshold', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('routing_intent_rules', sa.JSON(), nullable=True))
    op.add_column('skills', sa.Column('category', sa.String(length=64), nullable=False))
    op.add_column('skills', sa.Column('author', sa.String(length=128), nullable=False))
    op.add_column('tools', sa.Column('mcp_server_id', sa.BigInteger(), nullable=True))
    op.add_column('tools', sa.Column('mcp_tool_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'mcp_tool_name')
    op.drop_column('tools', 'mcp_server_id')
    op.drop_column('skills', 'author')
    op.drop_column('skills', 'category')
    op.drop_column('agents', 'routing_intent_rules')
    op.drop_column('agents', 'routing_threshold')
    op.drop_column('agents', 'routing_system_prompt')
    op.drop_column('agents', 'routing_model_id')
    op.drop_column('agents', 'routing_strategy')
    op.drop_column('agents', 'intent_entity_schema')
    op.drop_column('agents', 'intent_system_prompt')
    op.drop_column('agents', 'intent_confidence_threshold')
    op.drop_column('agents', 'intent_model_id')
    op.drop_column('agents', 'intent_recognition_enabled')
    op.drop_column('agents', 'max_tokens')
    op.drop_column('agents', 'temperature')
    op.drop_column('agents', 'status')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
